export const ADD_BLOG_REQUEST = "ADD_BLOG_REQUEST"
export const ADD_BLOG_SUCCESS = "ADD_BLOG_SUCCESS"
export const ADD_BLOG_FAIL = "ADD_BLOG_FAIL"


export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST"
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS"
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL"
export const UPDATE_BLOG_RESET = "UPDATE_BLOG_RESET"


export const ALL_BLOGS_REQUEST = "ALL_BLOGS_REQUEST"
export const ALL_BLOGS_SUCCESS = "ALL_BLOGS_SUCCESS"
export const ALL_BLOGS_FAIL = "ALL_BLOGS_FAIL"


export const SINGLE_BLOG_REQUEST = "SINGLE_BLOG_REQUEST"
export const SINGLE_BLOG_SUCCESS = "SINGLE_BLOG_SUCCESS"
export const SINGLE_BLOG_FAIL = "SINGLE_BLOG_FAIL"




export const CLEAR_ERRORS = "CLEAR_ERRORS";