export const ADD_PROJECT_REQUEST = "ADD_PROJECT_REQUEST"
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS"
export const ADD_PROJECT_FAIL = "ADD_PROJECT_FAIL"



export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST"
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS"
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL"
export const UPDATE_PROJECT_RESET = "UPDATE_PROJECT_RESET"


export const ALL_PROJECTS_REQUEST = "ALL_PROJECTS_REQUEST"
export const ALL_PROJECTS_SUCCESS = "ALL_PROJECTS_SUCCESS"
export const ALL_PROJECTS_FAIL = "ALL_PROJECTS_FAIL"


export const SINGLE_PROJECT_REQUEST = "SINGLE_PROJECT_REQUEST"
export const SINGLE_PROJECT_SUCCESS = "SINGLE_PROJECT_SUCCESS"
export const SINGLE_PROJECT_FAIL = "SINGLE_PROJECT_FAIL"




export const CLEAR_ERRORS = "CLEAR_ERRORS";