export const ADD_PROPERTY_REQUEST = "ADD_PROPERTY_REQUEST"
export const ADD_PROPERTY_SUCCESS = "ADD_PROPERTY_SUCCESS"
export const ADD_PROPERTY_FAIL = "ADD_PROPERTY_FAIL"

export const UPDATE_PROPERTY_REQUEST = "UPDATE_PROPERTY_REQUEST"
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS"
export const UPDATE_PROPERTY_RESET = "UPDATE_PROPERTY_RESET"
export const UPDATE_PROPERTY_FAIL = "UPDATE_PROPERTY_FAIL"


export const ALL_PROPERTIES_REQUEST = "ALL_PROPERTIES_REQUEST"
export const ALL_PROPERTIES_SUCCESS = "ALL_PROPERTIES_SUCCESS"
export const ALL_PROPERTIES_FAIL = "ALL_PROPERTIES_FAIL"



export const SINGLE_PROPERTY_REQUEST = "SINGLE_PROPERTY_REQUEST"
export const SINGLE_PROPERTY_SUCCESS = "SINGLE_PROPERTY_SUCCESS"
export const SINGLE_PROPERTY_FAIL = "SINGLE_PROPERTY_FAIL"


export const USER_PROPERTIES_REQUEST = "USER_PROPERTIES_REQUEST"
export const USER_PROPERTIES_SUCCESS = "USER_PROPERTIES_SUCCESS"
export const USER_PROPIESRTY_FAIL = "USER_PROPIESRTY_FAIL"


export const DELETE_PROPERTIES_REQUEST = "DELETE_PROPERTIES_REQUEST"
export const DELETE_PROPERTIES_SUCCESS = "DELETE_PROPERTIES_SUCCESS"
export const DELETE_PROPIESRTY_RESET = "DELETE_PROPIESRTY_RESET"
export const DELETE_PROPIESRTY_FAIL = "DELETE_PROPIESRTY_FAIL"



export const CLEAR_ERRORS = "CLEAR_ERRORS";