export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"


export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"


export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"

export const ADD_AGENT_REQUEST = "ADD_AGENT_REQUEST"
export const ADD_AGENT_SUCCESS = "ADD_AGENT_SUCCESS"
export const ADD_AGENT_FAIL = "ADD_AGENT_FAIL"

export const ALL_AGENTS_REQUEST = "ALL_AGENTS_REQUEST"
export const ALL_AGENTS_SUCCESS = "ALL_AGENTS_SUCCESS"
export const ALL_AGENTS_FAIL = "ALL_AGENTS_FAIL"


export const SINGLE_AGENT_REQUEST = "SINGLE_AGENT_REQUEST"
export const SINGLE_AGENT_SUCCESS = "SINGLE_AGENT_SUCCESS"
export const SINGLE_AGENT_FAIL = "SINGLE_AGENT_FAIL"

export const UPDATE_AGENT_REQUEST = "UPDATE_AGENT_REQUEST"
export const UPDATE_AGENT_SUCCESS = "UPDATE_AGENT_SUCCESS"
export const UPDATE_AGENT_RESET = "UPDATE_AGENT_RESET"
export const UPDATE_AGENT_FAIL = "UPDATE_AGENT_FAIL"



export const CLEAR_ERRORS = "CLEAR_ERRORS";